import { requireAppContext } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { getBookingSettings,getOpeningHours,getSalonProfile } from "@/services/app-data";
import { saveSettings } from "./actions";

const labels:Record<number,string>={0:"Zondag",1:"Maandag",2:"Dinsdag",3:"Woensdag",4:"Donderdag",5:"Vrijdag",6:"Zaterdag"};
const order=[1,2,3,4,5,6,0];
const short=(value:string|null)=>value?.slice(0,5)??"";

export default async function SettingsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const {salon,membership}=await requireAppContext();
  const [profile,booking,opening,query]=await Promise.all([getSalonProfile(salon.id),getBookingSettings(salon.id),getOpeningHours(salon.id),searchParams]);
  const map=new Map(opening.map(row=>[row.weekday,row]));
  const canManage=["owner","manager"].includes(membership.role);
  const error=typeof query.error==="string"?query.error:null;
  return <div data-settings-workspace>
    <header><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] sm:text-[36px]">Saloninstellingen</h1><p className="mt-1 text-sm text-[var(--muted)]">Beheer je salon en de regels voor online boeken.</p></header>
    {error?<p role="alert" className="mt-5 rounded-[10px] border border-[#e8c8c3] bg-[#fbefed] p-3.5 text-sm text-[var(--danger)]">{error}</p>:null}
    {canManage?<form action={saveSettings} className="mt-8 grid max-w-4xl gap-5">
      <section className="rounded-[16px] border border-[var(--border)] bg-white p-5"><h2 className="text-lg font-semibold">Hoe bereiken klanten ons?</h2><p className="mt-1 text-xs text-[var(--muted)]">Deze gegevens verschijnen bij online boeken en in berichten.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Naam" name="name" defaultValue={profile.name} required maxLength={120}/></div><Field label="Telefoon" name="phone" defaultValue={profile.phone??""}/><Field label="E-mail" name="email" type="email" defaultValue={profile.email??""}/><div className="sm:col-span-2"><Field label="Adres" name="address" defaultValue={profile.address??""}/></div><p className="sm:col-span-2 text-xs text-[var(--muted)]">Tijdzone {profile.timezone} · Valuta {profile.currency}</p></div></section>
      <section id="opening-hours" className="scroll-mt-24 rounded-[16px] border border-[var(--border)] bg-white p-5"><h2 className="text-lg font-semibold">Wanneer zijn we open?</h2><p className="mt-1 text-xs text-[var(--muted)]">Kies de dagen en tijden waarop de salon open is.</p><div className="mt-4 divide-y divide-[var(--border)] border-y border-[var(--border)]">{order.map(weekday=>{const row=map.get(weekday);const open=row?.is_open??false;return <div key={weekday} className="grid min-w-0 grid-cols-2 items-center gap-2 py-3 sm:grid-cols-[160px_1fr_1fr]"><label className="col-span-2 flex min-h-9 items-center gap-2 text-sm font-medium sm:col-span-1"><input type="checkbox" name={`open-${weekday}`} defaultChecked={open}/>{labels[weekday]}</label><input aria-label={`${labels[weekday]} open`} type="time" name={`start-${weekday}`} defaultValue={short(row?.start_time??null)||"09:00"} className="h-10 min-w-0 w-full rounded-[10px] border border-[var(--border)] bg-white px-2 outline-none focus:border-[var(--primary)] focus:ring-4 focus:ring-[var(--primary-soft)]"/><input aria-label={`${labels[weekday]} dicht`} type="time" name={`end-${weekday}`} defaultValue={short(row?.end_time??null)||"18:00"} className="h-10 min-w-0 w-full rounded-[10px] border border-[var(--border)] bg-white px-2 outline-none focus:border-[var(--primary)] focus:ring-4 focus:ring-[var(--primary-soft)]"/></div>})}</div></section>
      <section className="rounded-[16px] border border-[var(--border)] bg-white p-5"><h2 className="text-lg font-semibold">Hoe kunnen klanten boeken?</h2><p className="mt-1 text-xs text-[var(--muted)]">Bepaal wanneer klanten online een afspraak kunnen maken.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-medium"><span>Tijd tussen boekbare starttijden</span><select name="slotInterval" defaultValue={booking.slot_interval_minutes} className="h-11 rounded-[10px] border border-[var(--border)] bg-white px-3.5 outline-none focus:border-[var(--primary)] focus:ring-4 focus:ring-[var(--primary-soft)]">{[5,10,15,20,30,60].map(value=><option key={value} value={value}>{value} min</option>)}</select></label><Field label="Hoeveel minuten vooraf boeken?" name="minLead" type="number" min={0} defaultValue={booking.min_lead_minutes} required/><Field label="Hoeveel dagen vooruit boeken?" name="maxDays" type="number" min={1} max={365} defaultValue={booking.max_days_ahead} required/><label className="sm:col-span-2 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" name="allowStaffChoice" defaultChecked={booking.allow_staff_choice}/> Klant mag medewerker kiezen</label></div></section>
      <section className="rounded-[16px] border border-[var(--border)] bg-white p-5"><h2 className="text-lg font-semibold">Wanneer mogen klanten annuleren?</h2><div className="mt-4 max-w-sm"><Field label="Uren vóór de afspraak" name="cancellationHours" type="number" min={0} defaultValue={booking.cancellation_hours} required/></div></section>
      <div><Button size="lg">Instellingen opslaan</Button></div>
    </form>:<div className="mt-8 max-w-2xl rounded-[16px] border border-[var(--border)] bg-white p-5 text-sm"><p className="font-semibold">{profile.name}</p><p className="mt-1 text-[var(--muted)]">{profile.timezone} · {profile.currency}</p><p className="mt-5 text-[var(--muted)]">Alleen owner of manager kan operationele instellingen wijzigen.</p></div>}
    <section className="mt-8 max-w-4xl rounded-[16px] border border-[var(--border)] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[var(--muted)]">Online boekingspagina</p><a href={`/book/${salon.slug}`} target="_blank" rel="noreferrer" className="mt-2 inline-block font-medium text-[var(--primary)] hover:underline">/book/{salon.slug} ↗</a></section>
  </div>;
}
