import { requireAppContext } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { getBookingSettings,getOpeningHours,getSalonProfile } from "@/services/app-data";
import { saveSettings } from "./actions";

const labels:Record<number,string>={0:"Zondag",1:"Maandag",2:"Dinsdag",3:"Woensdag",4:"Donderdag",5:"Vrijdag",6:"Zaterdag"};
const order=[1,2,3,4,5,6,0];
const short=(value:string|null)=>value?.slice(0,5)??"";

export default async function SettingsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const {salon,membership}=await requireAppContext();
  const [profile,booking,opening,query]=await Promise.all([getSalonProfile(salon.id),getBookingSettings(salon.id),getOpeningHours(salon.id),searchParams]);
  const map=new Map(opening.map(row=>[row.weekday,row]));
  const canManage=["owner","manager"].includes(membership.role);
  const error=typeof query.error==="string"?query.error:null;
  return <div data-settings-workspace>
    <header><p className="text-xs font-semibold uppercase tracking-[.14em] text-[var(--accent)]">Settings</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] sm:text-[36px]">Saloninstellingen</h1><p className="mt-1 text-sm text-[var(--muted)]">Profiel, openingstijden en bookingregels in duidelijke delen.</p></header>
    {error?<p role="alert" className="mt-5 rounded-[14px] border border-[#e8c8c3] bg-[#fbefed] p-3.5 text-sm text-[var(--danger)]">{error}</p>:null}
    {canManage?<form action={saveSettings} className="mt-8 grid max-w-4xl gap-5">
      <section className="rounded-[24px] border border-[var(--border)] bg-white p-5"><h2 className="text-lg font-semibold">Salon</h2><p className="mt-1 text-xs text-[var(--muted)]">Basisgegevens die op booking en communicatie gebruikt kunnen worden.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Naam" name="name" defaultValue={profile.name} required maxLength={120}/></div><Field label="Telefoon" name="phone" defaultValue={profile.phone??""}/><Field label="E-mail" name="email" type="email" defaultValue={profile.email??""}/><div className="sm:col-span-2"><Field label="Adres" name="address" defaultValue={profile.address??""}/></div><p className="sm:col-span-2 text-xs text-[var(--muted)]">Timezone {profile.timezone} · Valuta {profile.currency}</p></div></section>
      <section className="rounded-[24px] border border-[var(--border)] bg-white p-5"><h2 className="text-lg font-semibold">Openingstijden</h2><p className="mt-1 text-xs text-[var(--muted)]">De basis waar medewerkers en beschikbaarheid binnen vallen.</p><div className="mt-4 grid gap-2">{order.map(weekday=>{const row=map.get(weekday);const open=row?.is_open??false;return <div key={weekday} className="grid grid-cols-[1fr_92px_92px] items-center gap-2 rounded-[14px] bg-[var(--background)] p-2.5 sm:grid-cols-[160px_1fr_1fr]"><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name={`open-${weekday}`} defaultChecked={open}/>{labels[weekday]}</label><input aria-label={`${labels[weekday]} open`} type="time" name={`start-${weekday}`} defaultValue={short(row?.start_time??null)||"09:00"} className="h-10 rounded-[11px] border border-[var(--border)] bg-white px-2"/><input aria-label={`${labels[weekday]} dicht`} type="time" name={`end-${weekday}`} defaultValue={short(row?.end_time??null)||"18:00"} className="h-10 rounded-[11px] border border-[var(--border)] bg-white px-2"/></div>})}</div></section>
      <section className="rounded-[24px] border border-[var(--border)] bg-white p-5"><h2 className="text-lg font-semibold">Booking</h2><p className="mt-1 text-xs text-[var(--muted)]">Alleen regels die direct invloed hebben op boekbare tijden.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-medium"><span>Slotinterval</span><select name="slotInterval" defaultValue={booking.slot_interval_minutes} className="h-11 rounded-[13px] border border-[var(--border)] bg-white px-3.5">{[5,10,15,20,30,60].map(value=><option key={value} value={value}>{value} min</option>)}</select></label><Field label="Minimaal vooraf boeken (min)" name="minLead" type="number" min={0} defaultValue={booking.min_lead_minutes} required/><Field label="Max. dagen vooruit" name="maxDays" type="number" min={1} max={365} defaultValue={booking.max_days_ahead} required/><Field label="Annuleringstermijn (uur)" name="cancellationHours" type="number" min={0} defaultValue={booking.cancellation_hours} required/><label className="sm:col-span-2 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" name="allowStaffChoice" defaultChecked={booking.allow_staff_choice}/> Klant mag medewerker kiezen</label></div></section>
      <div><Button size="lg">Instellingen opslaan</Button></div>
    </form>:<div className="mt-8 max-w-2xl rounded-[22px] border border-[var(--border)] bg-white p-5 text-sm"><p className="font-semibold">{profile.name}</p><p className="mt-1 text-[var(--muted)]">{profile.timezone} · {profile.currency}</p><p className="mt-5 text-[var(--muted)]">Alleen owner of manager kan operationele instellingen wijzigen.</p></div>}
    <section className="mt-8 max-w-4xl rounded-[22px] border border-[var(--border)] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[var(--muted)]">Publieke booking</p><a href={`/book/${salon.slug}`} target="_blank" rel="noreferrer" className="mt-2 inline-block font-medium text-[var(--accent-dark)]">/book/{salon.slug} ↗</a></section>
  </div>;
}
