import { describe,it,expect } from 'vitest';
import { getBalances,suggestTransfers,mutate,newGroup,makeExpense } from '../src/lib/domain';
import { emptyWorkspace } from '../src/lib/types';
function fixture(){const group=newGroup('Weekend','trip','EUR','Kwin',['Lisa','Tim']);const expense=makeExpense(group,{title:'Eten',amount:1000,paidBy:group.members[0].id,date:'2026-10-06',category:'food',splitMode:'equal',weights:group.members.map(()=>1),notes:'',receipt:null});return {group,state:mutate(mutate(emptyWorkspace(),{type:'create-group',group}),{type:'upsert-expense',groupId:group.id,expense})};}
describe('ledger',()=>{
 it('derives balance from exact allocations',()=>{const{state}=fixture();expect(getBalances(state.groups[0]).map(b=>b.total)).toEqual([666,-333,-333]);});
 it('settles all balances without changing original expense',()=>{let{state}=fixture();const initial=JSON.stringify(state.groups[0].expenses);for(const t of suggestTransfers(state.groups[0]))state=mutate(state,{type:'add-payment',groupId:state.groups[0].id,payment:{...t,id:crypto.randomUUID(),date:'2026-10-06',deletedAt:null}});expect(getBalances(state.groups[0]).every(b=>b.total===0)).toBe(true);expect(JSON.stringify(state.groups[0].expenses)).toBe(initial);});
 it('soft deletes and restores expense with history',()=>{let{state}=fixture();const group=state.groups[0],id=group.expenses[0].id;state=mutate(state,{type:'delete-expense',groupId:group.id,expenseId:id});expect(state.groups[0].expenses).toHaveLength(1);expect(getBalances(state.groups[0]).every(b=>b.total===0)).toBe(true);state=mutate(state,{type:'restore-expense',groupId:group.id,expenseId:id});expect(getBalances(state.groups[0])[0].total).toBe(666);expect(state.groups[0].activities.map(a=>a.action)).toContain('hersteld');});
 it('undoes a registered payment',()=>{let{state}=fixture();const t=suggestTransfers(state.groups[0])[0],id=crypto.randomUUID();state=mutate(state,{type:'add-payment',groupId:state.groups[0].id,payment:{...t,id,date:'2026-10-06',deletedAt:null}});state=mutate(state,{type:'delete-payment',groupId:state.groups[0].id,paymentId:id});expect(getBalances(state.groups[0]).map(b=>b.total)).toEqual([666,-333,-333]);});
 it('rejects overpayments and self payments',()=>{const{state}=fixture(),g=state.groups[0];expect(()=>mutate(state,{type:'add-payment',groupId:g.id,payment:{id:'p',from:g.members[1].id,to:g.members[0].id,amount:334,date:'2026-10-06',deletedAt:null}})).toThrow();expect(()=>mutate(state,{type:'add-payment',groupId:g.id,payment:{id:'p',from:g.members[0].id,to:g.members[0].id,amount:1,date:'2026-10-06',deletedAt:null}})).toThrow();});
 it('rejects invalid references and fabricated split totals',()=>{const{state}=fixture(),g=state.groups[0];const bad=structuredClone(g.expenses[0]);bad.splits[0].amount+=1;expect(()=>mutate(state,{type:'upsert-expense',groupId:g.id,expense:bad})).toThrow();bad.paidBy='unknown';expect(()=>mutate(state,{type:'upsert-expense',groupId:g.id,expense:bad})).toThrow();});
 it('does not alter original state',()=>{const{state}=fixture();const before=JSON.stringify(state);mutate(state,{type:'rename-group',groupId:state.groups[0].id,name:'Nieuw'});expect(JSON.stringify(state)).toBe(before);});
 it('keeps excluded participants out of expense',()=>{const{group}=fixture();const e=makeExpense(group,{title:'Taxi',amount:1000,paidBy:group.members[0].id,date:'2026-10-06',category:'transport',splitMode:'equal',weights:[1,0,1],notes:'',receipt:null});expect(e.splits.map(s=>s.amount)).toEqual([500,500]);expect(e.splits).toHaveLength(2);});
 it('rejects editing an archived group',()=>{let{state}=fixture();state=mutate(state,{type:'archive-group',groupId:state.groups[0].id,archived:true});expect(()=>mutate(state,{type:'upsert-expense',groupId:state.groups[0].id,expense:state.groups[0].expenses[0]})).toThrow();});
});
it('remembers the creator name atomically with the first group',()=>{const group=newGroup('Reis','trip','EUR','Kwin');expect(mutate(emptyWorkspace(),{type:'create-group',group}).profileName).toBe('Kwin');});
it('rejects stale concurrent expense edits',()=>{let{state}=fixture();const group=state.groups[0],original=structuredClone(group.expenses[0]),changed={...original,title:'Andere wijziging',updatedAt:'2026-10-06T12:00:00.000Z'};state=mutate(state,{type:'upsert-expense',groupId:group.id,expense:changed,expectedUpdatedAt:original.updatedAt});expect(()=>mutate(state,{type:'upsert-expense',groupId:group.id,expense:{...original,title:'Verouderde wijziging'},expectedUpdatedAt:original.updatedAt})).toThrow(/gewijzigd/);});
