import 'fake-indexeddb/auto';
import { it,expect } from 'vitest';
import { LocalRepository } from '../src/lib/repository';
import { newGroup } from '../src/lib/domain';
it('persists atomic mutations across repository instances',async()=>{const name=crypto.randomUUID(),a=new LocalRepository(name),b=new LocalRepository(name);const g=newGroup('Reis','trip','EUR','Kwin');await a.commit({type:'create-group',group:g});expect((await b.load()).groups[0].name).toBe('Reis');a.close();b.close();});
it('does not lose simultaneous writes from two tabs',async()=>{const name=crypto.randomUUID(),a=new LocalRepository(name),b=new LocalRepository(name);await Promise.all([a.commit({type:'create-group',group:newGroup('A','trip','EUR','Kwin')}),b.commit({type:'create-group',group:newGroup('B','trip','EUR','Kwin')})]);expect((await a.load()).groups.map(g=>g.name).sort()).toEqual(['A','B']);a.close();b.close();});
it('retains saved data when a mutation fails',async()=>{const a=new LocalRepository(crypto.randomUUID());const g=newGroup('Reis','trip','EUR','Kwin');await a.commit({type:'create-group',group:g});await expect(a.commit({type:'rename-group',groupId:g.id,name:''})).rejects.toThrow();expect((await a.load()).groups[0].name).toBe('Reis');a.close();});
it('does not overwrite corrupt persisted data',async()=>{const name=crypto.randomUUID(),a=new LocalRepository(name);await a.load();await new Promise<void>((resolve,reject)=>{const req=indexedDB.open(name,1);req.onsuccess=()=>{const db=req.result;const tx=db.transaction('workspace','readwrite');tx.objectStore('workspace').put({version:99},'current');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};});await expect(a.load()).rejects.toThrow();await expect(a.commit({type:'set-profile',name:'Kwin'})).rejects.toThrow();a.close();});
it('bounds stalled transactions and preserves data for retry',async()=>{const a=new LocalRepository(crypto.randomUUID(),30);const g=newGroup('Reis','trip','EUR','Kwin');await a.commit({type:'create-group',group:g});const real=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(){return {objectStore:()=>({get:()=>({})}),abort(){}} as unknown as IDBTransaction;};try{await expect(a.load()).rejects.toThrow(/reageert niet/);await expect(a.commit({type:'rename-group',groupId:g.id,name:'Nieuw'})).rejects.toThrow(/reageert niet/);}finally{IDBDatabase.prototype.transaction=real;}expect((await a.load()).groups[0].name).toBe('Reis');a.close();});
