'use client';
import { useState,useEffect,useCallback,useRef } from 'react';
import { Plus,ArrowUpRight,ArrowLeft,Layers,Archive,Settings2,Check,X,WifiOff,RefreshCw } from 'lucide-react';
import { repository } from '@/lib/repository';
import { sampleGroup,getBalances } from '@/lib/domain';
import { decodeSnapshot } from '@/lib/sharing';
import { money } from '@/lib/money';
import { type Workspace,type Action,type Expense,type Transfer,type Group } from '@/lib/types';
import { GroupIcon,Avatar,Loading,errorMessage,type Commit } from './ui';
import { GroupView,type Tab } from './group-view';
import { CreateGroup,ShareGroup,ImportCopy } from './group-forms';
import { ExpenseForm } from './expense-form';
import { PaymentForm } from './balance-view';
import { AppSettings } from './settings-view';
type Modal={type:'create'|'settings'}|{type:'expense';groupId:string;expense?:Expense}|{type:'payment';groupId:string;transfer:Transfer}|{type:'share';groupId:string}|{type:'copy';group:Group};
type Toast={message:string;undo?:Action;error?:boolean};
function Wordmark(){return <span className="wordmark"><svg viewBox="0 0 32 32" width="30" height="30" fill="none" aria-hidden><path d="M6 8h12a8 8 0 0 1 0 16H6V8Z" fill="currentColor"/><path d="M14 8h12v16H14a8 8 0 0 1 0-16Z" fill="currentColor" opacity=".35"/><path d="M16 10v12" stroke="#fafaf7" strokeWidth="2"/></svg>shared<span className="wordmark-light">money</span></span>;}
export default function App(){
 const [workspace,setWorkspace]=useState<Workspace|null>(null),[loadError,setLoadError]=useState(''),[activeId,setActiveId]=useState<string|null>(null),[tab,setTab]=useState<Tab>('expenses'),[modal,setModal]=useState<Modal|null>(null),[toast,setToast]=useState<Toast|null>(null),[archived,setArchived]=useState(false),[offline,setOffline]=useState(false),[undoing,setUndoing]=useState(false);
 const channel=useRef<BroadcastChannel|null>(null);
 const handleHash=useCallback(()=>{const hash=window.location.hash;if(hash.startsWith('#copy=')){try{setModal({type:'copy',group:decodeSnapshot(hash.slice(6))});}catch(e){setToast({message:errorMessage(e),error:true});}return;}setModal(null);setActiveId(hash.startsWith('#group=')?hash.slice(7):null);setTab('expenses');},[]);
 const load=useCallback(async()=>{try{const data=await repository.load();setWorkspace(data);setLoadError('');handleHash();}catch(e){setLoadError(errorMessage(e));}},[handleHash]);
 useEffect(()=>{let active=true;repository.load().then(data=>{if(active){setWorkspace(data);handleHash();}}).catch(e=>{if(active)setLoadError(errorMessage(e));});return()=>{active=false;};},[handleHash]);
 useEffect(()=>{
  const refresh=()=>repository.load().then(setWorkspace).catch(e=>setToast({message:errorMessage(e),error:true}));
  if('BroadcastChannel' in window){channel.current=new BroadcastChannel('shared-money');channel.current.onmessage=refresh;}
  const storage=(e:StorageEvent)=>{if(e.key==='shared-money-refresh')refresh();};
  const network=()=>setOffline(!navigator.onLine);queueMicrotask(network);
  window.addEventListener('storage',storage);window.addEventListener('hashchange',handleHash);window.addEventListener('popstate',handleHash);window.addEventListener('online',network);window.addEventListener('offline',network);
  if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
  return()=>{channel.current?.close();channel.current=null;window.removeEventListener('storage',storage);window.removeEventListener('hashchange',handleHash);window.removeEventListener('popstate',handleHash);window.removeEventListener('online',network);window.removeEventListener('offline',network);};
 },[handleHash]);
 const commit:Commit=async(action,message,undo)=>{const saved=await repository.commit(action);setWorkspace(saved);channel.current?.postMessage('saved');try{localStorage.setItem('shared-money-refresh',String(Date.now()));}catch{}if(message)setToast({message,undo});};
 function navigate(id:string|null){setModal(null);setActiveId(id);setTab('expenses');setArchived(false);window.history.pushState(null,'',id?`/#group=${id}`:'/');window.scrollTo({top:0,behavior:'instant'});}
 async function example(){if(!workspace)return;try{const existing=workspace.groups.find(g=>g.sample&&!g.archivedAt);if(existing){navigate(existing.id);return;}const g=sampleGroup(workspace.profileName||'Jij');await commit({type:'create-group',group:g},'Voorbeeldgroep geopend');navigate(g.id);}catch(e){setToast({message:errorMessage(e),error:true});}}
 async function undo(){if(!toast?.undo)return;setUndoing(true);try{const action=toast.undo;await commit(action,action.type==='delete-payment'?'Betaling teruggedraaid':'Uitgave hersteld');}catch(e){setToast({...toast,message:errorMessage(e),error:true});}finally{setUndoing(false);}}
 useEffect(()=>{if(!toast||toast.undo||toast.error)return;const timer=setTimeout(()=>setToast(null),15000);return()=>clearTimeout(timer);},[toast]);
 const modalGroup=modal&&'groupId' in modal?workspace?.groups.find(g=>g.id===modal.groupId):undefined;
 const group=workspace?.groups.find(g=>g.id===activeId),groups=workspace?.groups.filter(g=>!!g.archivedAt===archived)??[];
 return <div className="app-shell"><a className="skip-link" href="#main">Ga naar inhoud</a><aside className="sidebar"><button className="brand-button" onClick={()=>navigate(null)} aria-label="Shared Money, naar groepen"><Wordmark/></button><nav className="side-nav" aria-label="Hoofdnavigatie"><button className={!group&&!archived?'active':''} onClick={()=>{navigate(null);setArchived(false);}}><Layers size={19}/>Mijn groepen</button><button className={!group&&archived?'active':''} onClick={()=>{navigate(null);setArchived(true);}}><Archive size={18}/>Archief</button></nav><div className="sidebar-group-head"><span>Jouw groepen</span><button className="icon-button" aria-label="Nieuwe groep" onClick={()=>setModal({type:'create'})}><Plus size={17}/></button></div><nav className="sidebar-groups" aria-label="Groepen">{workspace?.groups.filter(g=>!g.archivedAt).map(g=><button className={g.id===group?.id?'active':''} key={g.id} onClick={()=>navigate(g.id)}><span className={`mini-group type-${g.type}`}><GroupIcon type={g.type}/></span><span>{g.name}</span></button>)}</nav><div className="sidebar-bottom"><p>Samen delen.<br/><strong>Zonder gedoe.</strong></p><button className="profile-button" onClick={()=>setModal({type:'settings'})}><Avatar name={workspace?.profileName||'Jij'} small/><span>Jouw gegevens</span><Settings2 size={17}/></button></div></aside>
 <div className="app-content"><header className="topbar"><button className="brand-button mobile-brand" onClick={()=>navigate(null)} aria-label="Shared Money, naar groepen"><Wordmark/></button><div className="desktop-breadcrumb"><button onClick={()=>navigate(null)}>Mijn groepen</button>{group?<><span>/</span><span>{group.name}</span></>:null}</div><div className="topbar-right"><span className="storage-status">{offline?<WifiOff size={14}/>:<span className="status-dot"/>}{offline?'Offline · lokaal bewaren':'Op dit apparaat'}</span><button className="icon-button mobile-settings" onClick={()=>setModal({type:'settings'})} aria-label="Jouw gegevens"><Settings2 size={19}/></button><button className="button secondary topbar-new" onClick={()=>setModal({type:'create'})}><Plus size={17}/>Nieuwe groep</button></div></header>
 <main id="main" className="main-content">{loadError?<div className="empty-state"><h1>Je gegevens konden niet worden geopend</h1><p role="alert">{loadError}</p><button className="button primary" onClick={load}><RefreshCw size={18}/>Opnieuw proberen</button></div>:!workspace?<Loading/>:group?<GroupView key={group.id} group={group} tab={tab} setTab={setTab} onExpense={expense=>setModal({type:'expense',groupId:group.id,expense})} onPay={transfer=>setModal({type:'payment',groupId:group.id,transfer})} onShare={()=>setModal({type:'share',groupId:group.id})} onBack={()=>navigate(null)} commit={commit}/>:<>
 <header className="home-header"><div><h1>{archived?'Je archief':'Jouw groepen'}</h1><p>{archived?'Afgerond, maar nog altijd terug te vinden.':'Samen beleven. Eerlijk verdelen.'}</p></div>{!archived?<button className="button primary" onClick={()=>setModal({type:'create'})}><Plus size={18}/>Nieuwe groep</button>:<button className="text-button" onClick={()=>setArchived(false)}><ArrowLeft size={17}/>Terug naar groepen</button>}</header>
 <nav className="home-tabs" aria-label="Groepslijst"><button className={!archived?'active':''} onClick={()=>setArchived(false)}>Groepen</button><button className={archived?'active':''} onClick={()=>setArchived(true)}>Archief</button></nav>{groups.length?<><div className="group-grid">{groups.map(g=>{const own=getBalances(g).find(b=>b.memberId===g.selfMemberId)!,count=g.expenses.filter(e=>!e.deletedAt).length;return <button className="group-card" key={g.id} onClick={()=>navigate(g.id)}><div className="group-card-top"><span className={`group-symbol type-${g.type}`}><GroupIcon type={g.type}/></span><ArrowUpRight size={20}/></div><h2>{g.name}</h2><p>{g.members.length} {g.members.length===1?'deelnemer':'deelnemers'} · {count} {count===1?'uitgave':'uitgaven'}{g.sample?' · Voorbeeld':''}</p><div className="group-card-bottom"><span className="avatar-stack">{g.members.slice(0,4).map((m,i)=><Avatar name={m.name} index={i} key={m.id} small/>)}</span><span className="card-balance"><small>{own.total>0?'Jij krijgt terug':own.total<0?'Jij betaalt nog':'In balans'}</small><strong className={own.total>0?'positive':''}>{money(Math.abs(own.total),g.currency)}</strong></span></div></button>})}<button className="new-group-card" onClick={()=>setModal({type:'create'})}><span><Plus size={24}/></span><strong>Nieuwe herinneringen,<br/>nieuwe groep.</strong><small>Maak een groep aan<ArrowUpRight size={14}/></small></button></div><p className="home-footnote">Een reis, jullie huis of een etentje. Iedere groep houdt zijn eigen balans.</p></>:<div className="welcome-empty"><div className="welcome-art" aria-hidden><span className="art-receipt"><span/><span/><span/><strong>50 / 50</strong></span><span className="art-circle circle-one">L</span><span className="art-circle circle-two">K</span><span className="art-circle circle-three">T</span></div><h2>{archived?'Je archief is nog leeg':'Het begint met samen.'}</h2><p>{archived?'Archiveer een afgeronde groep via het onderdeel Groep. Alle uitgaven blijven bewaard.':'Van een weekend weg tot een gedeelde koelkast. Maak een groep, voeg uitgaven toe en weet meteen wie wat terugkrijgt.'}</p>{!archived?<><button className="button primary" onClick={()=>setModal({type:'create'})}>Maak je eerste groep<ArrowUpRight size={18}/></button><button className="text-button" onClick={example}>Of bekijk een voorbeeldgroep</button></>:null}</div>}
 {!archived?<div className="home-bottom-note"><Check size={17}/><p>Geen account. Geen bankkoppeling. Gewoon eerlijk delen.</p></div>:null}
 </>}</main></div>
 {workspace&&modal?.type==='create'?<CreateGroup profileName={workspace.profileName} commit={commit} onClose={()=>setModal(null)} onCreated={navigate}/>:null}
 {modalGroup&&modal?.type==='expense'?<ExpenseForm group={modalGroup} expense={modal.expense} commit={commit} onClose={()=>setModal(null)}/>:null}
 {modalGroup&&modal?.type==='payment'?<PaymentForm group={modalGroup} transfer={modal.transfer} commit={commit} onClose={()=>setModal(null)}/>:null}
 {modalGroup&&modal?.type==='share'?<ShareGroup group={modalGroup} onClose={()=>setModal(null)}/>:null}
 {workspace&&modal?.type==='settings'?<AppSettings workspace={workspace} commit={commit} onClose={()=>setModal(null)} onImported={navigate}/>:null}
 {workspace&&modal?.type==='copy'?<ImportCopy group={modal.group} profileName={workspace.profileName} commit={commit} onClose={()=>{setModal(null);if(window.location.hash.startsWith('#copy='))window.history.replaceState(null,'','/');}} onCreated={navigate}/>:null}
 {toast?<div className={`toast ${toast.error?'error':''}`}><span className="toast-icon">{toast.error?<RefreshCw size={18}/>:<Check size={18}/>}</span><span role={toast.error?'alert':'status'}>{toast.message}</span>{toast.undo?<button onClick={undo} disabled={undoing}>{undoing?'Herstellen…':'Ongedaan maken'}</button>:null}<button className="toast-close" aria-label="Melding sluiten" onClick={()=>setToast(null)}><X size={16}/></button></div>:null}
 </div>;
}
