'use client';
import { useState } from 'react';
import { ArrowRight,Check,ArrowUpRight } from 'lucide-react';
import { getBalances,suggestTransfers } from '@/lib/domain';
import { money,amountInput,parseMinor } from '@/lib/money';
import { memberName,uid,today,type Group,type Transfer } from '@/lib/types';
import { Avatar,Dialog,FormError,dateLabel,errorMessage,type Commit } from './ui';
export function BalanceView({group,onPay,commit}:{group:Group;onPay:(t:Transfer)=>void;commit:Commit}){
 const balances=getBalances(group),transfers=suggestTransfers(group),payments=group.payments.filter(p=>!p.deletedAt);
 const [error,setError]=useState(''),[pending,setPending]=useState<string|null>(null);
 async function undo(id:string){setPending(id);setError('');try{await commit({type:'delete-payment',groupId:group.id,paymentId:id},'Betaling teruggedraaid');}catch(e){setError(errorMessage(e));}finally{setPending(null);}}
 return <div className="balance-view"><div className="section-heading"><h2>Zo staat het ervoor</h2><span className="muted">{group.currency}</span></div><p className="section-description">Alles wat is betaald, eerlijk verdeeld. Tik op een saldo voor de berekening.</p>
 <div className="balance-list">{balances.map((b,i)=><details key={b.memberId} className="balance-item"><summary><span className="member-label"><Avatar name={memberName(group,b.memberId)} index={i}/><span><strong>{memberName(group,b.memberId)}{b.memberId===group.selfMemberId?<small className="inline-self">jij</small>:null}</strong><small>{b.total>0?'krijgt terug':b.total<0?'betaalt nog':'is in balans'}</small></span></span><strong className={`balance-amount ${b.total>0?'positive':''}`}>{money(Math.abs(b.total),group.currency)}</strong></summary><div className="balance-explanation"><div><span>Voorgeschoten</span><span>{money(b.paid,group.currency)}</span></div><div><span>Eigen deel van uitgaven</span><span>− {money(b.share,group.currency)}</span></div><div><span>Terugbetaald aan anderen</span><span>+ {money(b.sent,group.currency)}</span></div><div><span>Ontvangen van anderen</span><span>− {money(b.received,group.currency)}</span></div><div className="explanation-total"><strong>{b.total>=0?'Krijgt terug':'Betaalt nog'}</strong><strong>{money(Math.abs(b.total),group.currency)}</strong></div></div></details>)}</div>
 <div className="section-heading space-above"><h2>{transfers.length?'Met deze betalingen klopt het weer':'Iedereen is in balans'}</h2>{!transfers.length?<span className="status-check"><Check size={18}/></span>:null}</div>
 {transfers.length?<><p className="section-description">Deze suggesties beperken het heen en weer betalen.</p><div className="transfer-list">{transfers.map((t,i)=><div className="transfer-row" key={`${t.from}-${t.to}`}><div className="transfer-who"><Avatar name={memberName(group,t.from)} index={group.members.findIndex(m=>m.id===t.from)} small/><span><strong>{memberName(group,t.from)}</strong><small>betaalt {memberName(group,t.to)}</small></span></div><strong className="tabular">{money(t.amount,group.currency)}</strong>{!group.archivedAt?<button className="button secondary compact" onClick={()=>onPay(t)} aria-label={`Verrekening vastleggen van ${memberName(group,t.from)} aan ${memberName(group,t.to)}`}>Vastleggen<ArrowUpRight size={15}/></button>:null}<span className="visually-hidden">Suggestie {i+1}</span></div>)}</div><p className="fine-print">Geld overmaken doe je zelf. Hier leg je alleen vast wat al betaald is.</p></>:<p className="section-description">Er staan geen gezamenlijke bedragen meer open.</p>}
 {payments.length?<><div className="section-heading space-above"><h2>Vastgelegde betalingen</h2></div><div className="payments-list">{payments.map(p=><div className="payment-row" key={p.id}><div><strong>{memberName(group,p.from)}<ArrowRight size={14}/>{memberName(group,p.to)}</strong><small>{dateLabel(p.date)}</small></div><strong>{money(p.amount,group.currency)}</strong>{!group.archivedAt?<button className="text-button" disabled={pending===p.id} onClick={()=>undo(p.id)}>Terugdraaien</button>:null}</div>)}</div></>:null}<FormError message={error}/></div>;
}
export function PaymentForm({group,transfer,commit,onClose}:{group:Group;transfer:Transfer;commit:Commit;onClose:()=>void}){
 const [amount,setAmount]=useState(amountInput(transfer.amount)),[date,setDate]=useState(today()),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const payment={...transfer,id:uid(),amount:parseMinor(amount),date,deletedAt:null};if(payment.amount>transfer.amount)throw new Error('Je kunt maximaal het voorgestelde bedrag vastleggen.');await commit({type:'add-payment',groupId:group.id,payment},'Betaling vastgelegd',{type:'delete-payment',groupId:group.id,paymentId:payment.id});onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <Dialog title="Betaling vastleggen" onClose={onClose}><form className="form" onSubmit={submit}><div className="payment-direction"><Avatar name={memberName(group,transfer.from)} index={group.members.findIndex(m=>m.id===transfer.from)}/><ArrowRight size={20}/><Avatar name={memberName(group,transfer.to)} index={group.members.findIndex(m=>m.id===transfer.to)}/></div><p><strong>{memberName(group,transfer.from)}</strong> betaalt <strong>{memberName(group,transfer.to)}</strong>.</p><label>Betaald bedrag ({group.currency})<input aria-label="Betaald bedrag" inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)} autoFocus maxLength={12}/></label><label>Betaaldatum<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><div className="notice"><strong>Is dit bedrag al overgemaakt?</strong><p>Deze knop registreert de betaling. Er wordt geen geld verstuurd.</p></div><FormError message={error}/><button className="button primary full" disabled={busy}>{busy?'Vastleggen…':'Betaling vastleggen'}<Check size={18}/></button></form></Dialog>;
}
