'use client';
import { useState,useRef } from 'react';
import Image from 'next/image';
import { ChevronDown,Paperclip,Trash2,X,Check } from 'lucide-react';
import { makeExpense } from '@/lib/domain';
import { parseMinor,parseWeight,splitAmount,money,amountInput } from '@/lib/money';
import { categoryNames,today,type Group,type Expense,type SplitMode,type Category } from '@/lib/types';
import { Dialog,FormError,Avatar,Icon,errorMessage,type Commit } from './ui';
const participates=(value:string|undefined)=>Number((value||'0').replace(',','.'))>0;
const modeNames:Record<SplitMode,string>={equal:'Gelijk',shares:'Aandelen',exact:'Exact',percentage:'Percentage'};
const quickCategories:{key:Category;label:string}[]=[{key:'food',label:'Eten'},{key:'transport',label:'Vervoer'},{key:'groceries',label:'Boodschappen'},{key:'stay',label:'Verblijf'},{key:'fun',label:'Plezier'},{key:'other',label:'Anders'}];
function valuesFor(g:Group,e?:Expense){return Object.fromEntries(g.members.map(m=>{const s=e?.splits.find(s=>s.memberId===m.id);return [m.id,e?.splitMode==='equal'||!e?(s||!e?'1':'0'):s?String(s.weight/100).replace('.',','):'0'];}));}
export function ExpenseForm({group,expense,commit,onClose}:{group:Group;expense?:Expense;commit:Commit;onClose:()=>void}){
 const [amount,setAmount]=useState(expense?amountInput(expense.amount):''),[title,setTitle]=useState(expense?.title??''),[payer,setPayer]=useState(expense?.paidBy??group.selfMemberId),[date,setDate]=useState(expense?.date??today()),[category,setCategory]=useState<Category>(expense?.category??'other'),[mode,setMode]=useState<SplitMode>(expense?.splitMode??'equal'),[values,setValues]=useState<Record<string,string>>(()=>valuesFor(group,expense)),[notes,setNotes]=useState(expense?.notes??''),[receipt,setReceipt]=useState<string|null>(expense?.receipt??null),[advanced,setAdvanced]=useState(!!expense&&expense.splitMode!=='equal'),[details,setDetails]=useState(!!expense?.notes||!!expense?.receipt),[error,setError]=useState(''),[busy,setBusy]=useState(false),[attaching,setAttaching]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null);
 function weights():number[]{return group.members.map(m=>mode==='equal'?(participates(values[m.id])?1:0):parseWeight(values[m.id]||'0'));}
 let preview:number[]=[];try{preview=splitAmount(parseMinor(amount),mode,weights());}catch{}
 function changeMode(m:SplitMode){setMode(m);setError('');const active=group.members.filter(member=>participates(values[member.id]));setValues(Object.fromEntries(group.members.map((member,i)=>[member.id,m==='equal'||m==='shares'?(active.some(a=>a.id===member.id)?'1':'0'):m==='percentage'?(active.some(a=>a.id===member.id)?String(Math.floor(10000/active.length)/100+(active[0]?.id===member.id?(10000%active.length)/100:0)).replace('.',','):'0'):preview.length?amountInput(preview[i]):'0'])));}
 async function attach(file?:File){if(!file)return;setError('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Kies een JPG-, PNG- of WebP-afbeelding.');return;}if(file.size>2_000_000){setError('Deze bon is te groot. Kies een foto kleiner dan 2 MB.');return;}setAttaching(true);try{const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result as string);r.onerror=()=>reject(new Error('De foto kon niet worden gelezen. Probeer een andere foto.'));r.readAsDataURL(file);});setReceipt(data);setDetails(true);}catch(e){setError(errorMessage(e));}finally{setAttaching(false);if(fileRef.current)fileRef.current.value='';}}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const record=makeExpense(group,{title,amount:parseMinor(amount),paidBy:payer,date,category,splitMode:mode,weights:weights(),notes,receipt},expense);await commit({type:'upsert-expense',groupId:group.id,expense:record,expectedUpdatedAt:expense?.updatedAt},expense?'Uitgave gewijzigd':'Uitgave toegevoegd · score bijgewerkt');onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function remove(){if(!expense)return;setBusy(true);try{await commit({type:'delete-expense',groupId:group.id,expenseId:expense.id},'Uitgave verwijderd',{type:'restore-expense',groupId:group.id,expenseId:expense.id});onClose();}catch(e){setError(errorMessage(e));setBusy(false);}}
 if(group.archivedAt&&expense)return <Dialog title={expense.title} onClose={onClose}><div className="form"><div className="notice"><strong>Deze groep is gearchiveerd</strong><p>Haal de groep uit het archief om deze uitgave te wijzigen.</p></div><strong className="your-amount">{money(expense.amount,group.currency)}</strong><p>{group.members.find(m=>m.id===expense.paidBy)?.name} betaalde · {expense.date}</p>{expense.splits.map(s=><div className="readonly-split" key={s.memberId}><span>{group.members.find(m=>m.id===s.memberId)?.name}</span><strong>{money(s.amount,group.currency)}</strong></div>)}{expense.notes?<p>{expense.notes}</p>:null}{expense.receipt?<Image src={expense.receipt} width={500} height={300} alt="Bijgevoegde bon" className="readonly-receipt"/>:null}</div></Dialog>;
 return <Dialog title={expense?'Uitgave bekijken & wijzigen':'Nieuwe uitgave'} onClose={onClose} wide><form className="form expense-form playful-expense" onSubmit={submit}>
  <label className="amount-field"><span>Bedrag</span><div className="amount-input"><span className="currency">{group.currency==='EUR'?'€':group.currency}</span><input aria-label="Bedrag" inputMode="decimal" autoFocus required placeholder="0,00" value={amount} onChange={e=>setAmount(e.target.value)} maxLength={12}/></div></label>
  <label>Omschrijving<input required maxLength={160} placeholder="Waar was het voor?" value={title} onChange={e=>setTitle(e.target.value)}/></label>
  <fieldset className="quick-categories"><legend>Snelle categorie</legend>{quickCategories.map(item=><button type="button" key={item.key} aria-pressed={category===item.key} className={category===item.key?'selected':''} onClick={()=>setCategory(item.key)}><span><Icon category={item.key}/></span>{item.label}</button>)}</fieldset>
  <div className="two-fields"><label>Betaald door<select value={payer} onChange={e=>setPayer(e.target.value)}>{group.members.map(m=><option value={m.id} key={m.id}>{m.name}{m.id===group.selfMemberId?' (jij)':''}</option>)}</select></label><label>Datum<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label></div>
  <button type="button" className="disclosure" onClick={()=>setAdvanced(!advanced)} aria-expanded={advanced}><span><strong>Verdeling aanpassen</strong><small>{modeNames[mode]} · {group.members.filter(m=>participates(values[m.id])).length} deelnemers</small></span><ChevronDown size={18} className={advanced?'rotate':''}/></button>
  {advanced?<div className="split-panel"><div className="split-tabs" role="group" aria-label="Verdeling">{Object.entries(modeNames).map(([key,label])=><button type="button" aria-pressed={mode===key} className={mode===key?'selected':''} onClick={()=>changeMode(key as SplitMode)} key={key}>{label}</button>)}</div>
   <p className="field-note">{mode==='equal'?'Iedereen deelt gelijk mee. Tik om iemand uit te sluiten.':mode==='shares'?'Geef bijvoorbeeld 1 aandeel aan een volwassene en 0,5 aan een kind.':mode==='exact'?'Vul per persoon het exacte bedrag in. De som moet kloppen.':'Verdeel precies 100% over de deelnemers.'}</p>
   {group.members.map((m,i)=><div className="split-row" key={m.id}><span className="member-label"><Avatar name={m.name} index={i} small/><span>{m.name}</span></span>{mode==='equal'?<label className="check-label"><input type="checkbox" aria-label={`${m.name} deelt mee`} checked={participates(values[m.id])} onChange={e=>setValues({...values,[m.id]:e.target.checked?'1':'0'})}/><span className={participates(values[m.id])?'check selected':'check'}><Check size={15}/></span><span className="tabular">{preview.length?money(preview[i],group.currency):'—'}</span></label>:<div className="split-value"><input aria-label={`${mode==='exact'?'Bedrag':mode==='percentage'?'Percentage':'Aandelen'} voor ${m.name}`} inputMode="decimal" value={values[m.id]} onChange={e=>setValues({...values,[m.id]:e.target.value})} maxLength={12}/><span>{mode==='percentage'?'%':mode==='shares'?'×':group.currency==='EUR'?'€':group.currency}</span></div>}</div>)}
   {mode!=='equal'?<div className="split-total"><span>{mode==='percentage'?'Totaal percentage':'Totaal verdeeld'}</span><strong>{mode==='percentage'?`${group.members.reduce((s,m)=>s+(Number((values[m.id]||'0').replace(',','.'))||0),0).toLocaleString('nl-NL',{maximumFractionDigits:2})}%`:preview.length?money(preview.reduce((a,b)=>a+b,0),group.currency):'Controleer de verdeling'}</strong></div>:null}
  </div>:null}
  <button type="button" className="text-button details-toggle" onClick={()=>setDetails(!details)} aria-expanded={details}>{details?'Minder details':'Notitie of bon toevoegen'}<ChevronDown size={16} className={details?'rotate':''}/></button>
  {details?<div className="form expense-details"><label>Categorie<select value={category} onChange={e=>setCategory(e.target.value as Category)}>{Object.entries(categoryNames).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Notitie <span className="optional">optioneel</span><textarea value={notes} maxLength={1000} onChange={e=>setNotes(e.target.value)} rows={2} placeholder="Iets om te onthouden?"/></label><input className="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" ref={fileRef} tabIndex={-1} onChange={e=>attach(e.target.files?.[0])}/>{receipt?<div className="receipt-preview"><Image src={receipt} width={500} height={300} alt="Bijgevoegde bon"/><button type="button" className="icon-button" aria-label="Bon verwijderen" onClick={()=>setReceipt(null)}><X size={18}/></button></div>:<button type="button" className="button secondary" onClick={()=>fileRef.current?.click()} disabled={attaching}><Paperclip size={17}/>{attaching?'Bon lezen…':'Bonfoto toevoegen'}</button>}<p className="fine-print">Alleen op dit apparaat · max. 2 MB · geen automatische bonherkenning</p></div>:null}
  <FormError message={error}/><button className="button primary full playful-save" disabled={busy||attaching}>{busy?'Opslaan…':expense?'Wijzigingen opslaan':'Uitgave opslaan'}</button>
  {expense?<button type="button" className="text-button danger centered" onClick={remove} disabled={busy}><Trash2 size={16}/>Uitgave verwijderen</button>:null}
 </form></Dialog>;
}
