'use client';
import { useState,useMemo } from 'react';
import { Search,Plus,ArrowUpRight,Paperclip,Receipt,Share2,ArrowLeft } from 'lucide-react';
import { getBalances,suggestTransfers } from '@/lib/domain';
import { money } from '@/lib/money';
import { memberName,categoryNames,type Group,type Expense,type Transfer } from '@/lib/types';
import { Icon,Avatar,dateLabel,type Commit } from './ui';
import { BalanceView } from './balance-view';
import { GroupSettings } from './settings-view';
export type Tab='expenses'|'balance'|'group';
export function GroupView({group,tab,setTab,onExpense,onPay,onShare,onBack,commit}:{group:Group;tab:Tab;setTab:(t:Tab)=>void;onExpense:(expense?:Expense)=>void;onPay:(t:Transfer)=>void;onShare:()=>void;onBack:()=>void;commit:Commit}){
 const [search,setSearch]=useState(''),[category,setCategory]=useState('all');
 const expenses=group.expenses.filter(e=>!e.deletedAt);
 const filtered=useMemo(()=>group.expenses.filter(e=>!e.deletedAt&&(category==='all'||e.category===category)&&`${e.title} ${e.notes} ${memberName(group,e.paidBy)}`.toLocaleLowerCase('nl').includes(search.toLocaleLowerCase('nl').trim())).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)),[group,category,search]);
 const balances=getBalances(group),self=balances.find(b=>b.memberId===group.selfMemberId)!,total=expenses.reduce((sum,e)=>sum+e.amount,0),allTransfers=suggestTransfers(group),transfers=allTransfers.filter(t=>t.from===self.memberId||t.to===self.memberId),settled=allTransfers.length===0;
 const nextPayer=[...balances].sort((a,b)=>a.total-b.total)[0];
 return <><header className="group-header"><button className="mobile-back text-button" onClick={onBack}><ArrowLeft size={18}/> Groepen</button><div className="group-title-row"><div><h1>{group.name}</h1><div className="group-meta"><span className="avatar-stack">{group.members.slice(0,4).map((m,i)=><Avatar key={m.id} name={m.name} index={i} small/>)}</span><span>{group.members.length} {group.members.length===1?'deelnemer':'deelnemers'} · {group.currency}{group.sample?' · Voorbeeldgroep':''}{group.archivedAt?' · Gearchiveerd':''}</span></div></div><button className="button secondary share-button" onClick={onShare}><Share2 size={17}/><span>Deel kopie</span></button></div></header>
 <div className="group-layout"><div className="group-main"><div className="mobile-summary"><span>{self.total>0?'Jij krijgt terug':self.total<0?'Jij betaalt nog':'Jij bent in balans'}</span><strong className="tabular">{money(Math.abs(self.total),group.currency)}</strong>{!group.archivedAt?<button className="button primary" onClick={()=>onExpense()}><Plus size={18}/> Uitgave toevoegen</button>:null}</div>
 <section className={`group-score ${settled?'is-settled':''}`} aria-label="Groepsscore"><div className="score-heading"><span className="score-kicker">Groepsscore</span><strong>{settled?'Iedereen staat quitte 🎉':`${allTransfers.length} ${allTransfers.length===1?'verrekening':'verrekeningen'} te gaan`}</strong><small>{settled?'Ronde klaar. Tijd voor de volgende herinnering.':'Iedere uitgave werkt de stand meteen bij.'}</small></div><div className="score-players">{balances.map((balance,i)=><div className={`score-player ${balance.total>0?'score-positive':balance.total<0?'score-negative':'score-even'}`} key={balance.memberId}><Avatar name={memberName(group,balance.memberId)} index={i}/><span><strong>{memberName(group,balance.memberId)}</strong><small>{balance.memberId===group.selfMemberId?'Jij':balance.total>0?'Krijgt terug':balance.total<0?'Betaalt nog':'Quitte'}</small></span><b>{balance.total===0?'✓':`${balance.total>0?'+':'−'}${money(Math.abs(balance.total),group.currency)}`}</b></div>)}</div><div className="score-footer"><span><small>Samen uitgegeven</small><strong>{money(total,group.currency)}</strong></span><span><small>Jouw aandeel</small><strong>{money(self.share,group.currency)}</strong></span><span><small>Uitgaven</small><strong>{expenses.length}</strong></span></div></section>
 <nav className="group-tabs" role="tablist" aria-label="Groepsonderdelen">{([['expenses','Uitgaven'],['balance','Balans'],['group','Groep']] as const).map(([key,label])=><button key={key} id={`tab-${key}`} role="tab" aria-selected={tab===key} aria-controls="group-panel" className={tab===key?'active':''} onClick={()=>setTab(key)} onKeyDown={e=>{const tabs:Tab[]=['expenses','balance','group'];let target:Tab|undefined;if(e.key==='ArrowRight')target=tabs[(tabs.indexOf(key)+1)%3];if(e.key==='ArrowLeft')target=tabs[(tabs.indexOf(key)+2)%3];if(e.key==='Home')target=tabs[0];if(e.key==='End')target=tabs[2];if(target){e.preventDefault();setTab(target);document.getElementById(`tab-${target}`)?.focus();}}} tabIndex={tab===key?0:-1}>{label}{key==='expenses'?<span>{expenses.length}</span>:null}</button>)}</nav>
 <div role="tabpanel" id="group-panel" aria-labelledby={`tab-${tab}`} tabIndex={0}>
 {tab==='expenses'?<><div className="expenses-toolbar"><label className="search-field"><Search size={18}/><input type="search" aria-label="Zoek uitgaven" placeholder="Zoek een uitgave" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="category-filter" aria-label="Filter op categorie" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Alle categorieën</option>{Object.entries(categoryNames).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></div>
 {!expenses.length?<div className="empty-state group-empty"><span className="empty-icon"><Receipt size={30} strokeWidth={1.3}/></span><h2>Nog geen uitgaven</h2><p>De eerste koffie? De hele vakantie?<br/>Voeg toe wat iemand heeft voorgeschoten.</p>{!group.archivedAt?<button className="button primary" onClick={()=>onExpense()}><Plus size={18}/> Uitgave toevoegen</button>:null}</div>:!filtered.length?<div className="empty-state search-empty"><Search size={28}/><h2>Geen uitgaven gevonden</h2><p>Probeer een andere zoekterm of categorie.</p><button className="text-button" onClick={()=>{setSearch('');setCategory('all');}}>Filters wissen</button></div>:<div className="expense-list">{filtered.map((e,i)=><div key={e.id}>{i===0||filtered[i-1].date!==e.date?<div className="expense-date">{dateLabel(e.date)} {e.date.slice(0,4)!==String(new Date().getFullYear())?e.date.slice(0,4):''}</div>:null}<button className="expense-row" aria-label={`Open uitgave ${e.title}`} onClick={()=>onExpense(e)}><span className={`expense-category category-${e.category}`}><Icon category={e.category}/></span><span className="expense-description"><strong>{e.title}{e.receipt?<Paperclip size={13}/>:null}</strong><small>{memberName(group,e.paidBy)} betaalde · {e.splits.length} {e.splits.length===1?'persoon':'personen'}</small></span><span className="expense-numbers"><strong>{money(e.amount,group.currency)}</strong><small>jouw deel {money(e.splits.find(s=>s.memberId===self.memberId)?.amount??0,group.currency)}</small></span></button></div>)}<div className="list-total"><span>{search||category!=='all'?'Totaal gevonden uitgaven':'Samen uitgegeven'}</span><strong>{money(filtered.reduce((sum,e)=>sum+e.amount,0),group.currency)}</strong></div></div>}</>:tab==='balance'?<BalanceView group={group} onPay={onPay} commit={commit}/>:<GroupSettings key={group.id} group={group} commit={commit}/>}
 </div></div><aside className="group-aside"><div className="your-balance"><p>{self.total>0?'Jij krijgt terug':self.total<0?'Jij betaalt nog':'Jij bent in balans'}</p><strong className="your-amount">{money(Math.abs(self.total),group.currency)}</strong><span className="balance-caption">{memberName(group,self.memberId)} · jouw overzicht</span>{!group.archivedAt?<button className="button primary full" onClick={()=>onExpense()}><Plus size={18}/>Uitgave toevoegen</button>:null}{transfers.length?<div className="your-transfers">{transfers.slice(0,3).map(t=><p key={`${t.from}-${t.to}`}><span>{t.from===self.memberId?`Aan ${memberName(group,t.to)}`:`Van ${memberName(group,t.from)}`}</span><strong>{money(t.amount,group.currency)}</strong></p>)}<button className="text-button" onClick={()=>setTab('balance')}>Bekijk de balans<ArrowUpRight size={16}/></button></div>:<p className="fine-print">Alles is netjes verdeeld.</p>}</div>
 <div className="group-facts"><div><span>Samen uitgegeven</span><strong>{money(total,group.currency)}</strong></div><div><span>Jouw aandeel</span><strong>{money(self.share,group.currency)}</strong></div><div><span>Uitgaven</span><strong>{expenses.length}</strong></div></div>
 {nextPayer?.total<0&&expenses.length?<div className="next-payer"><Avatar name={memberName(group,nextPayer.memberId)} index={group.members.findIndex(m=>m.id===nextPayer.memberId)} small/><p><strong>{memberName(group,nextPayer.memberId)} kan de volgende betalen</strong><span>Dat brengt jullie dichter bij een gelijke balans.</span></p></div>:null}<p className="local-note">Op dit apparaat bewaard.<br/>Maak een reservekopie via Jouw gegevens.</p>
 </aside></div></>;
}
