'use client';
import { useState,useRef } from 'react';
import { Plus,Download,Upload,Archive,History,ChevronDown } from 'lucide-react';
import { Avatar,Dialog,FormError,errorMessage,type Commit } from './ui';
import { newMember } from './group-forms';
import { exportCsv,downloadFile,parseBackup,independentCopy } from '@/lib/sharing';
import { MAX_BACKUP_BYTES } from '@/lib/schema';
import { type Group,type Member,type Workspace,groupTypeNames } from '@/lib/types';
export function GroupSettings({group,commit}:{group:Group;commit:Commit}){
 const [name,setName]=useState(group.name),[member,setMember]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function rename(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await commit({type:'rename-group',groupId:group.id,name},'Groepsnaam gewijzigd');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function add(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await commit({type:'add-member',groupId:group.id,member:newMember(member)},'Deelnemer toegevoegd');setMember('');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function identity(memberId:string){try{await commit({type:'set-self',groupId:group.id,memberId});}catch(e){setError(errorMessage(e));}}
 async function archive(){setBusy(true);try{await commit({type:'archive-group',groupId:group.id,archived:!group.archivedAt},group.archivedAt?'Groep uit archief gehaald':'Groep gearchiveerd');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <div className="group-settings"><div className="section-heading"><h2>Jullie groep</h2><span className="muted">{groupTypeNames[group.type]} · {group.currency}</span></div><form className="inline-form group-name-form" onSubmit={rename}><label>Groepsnaam<input value={name} onChange={e=>setName(e.target.value)} required maxLength={120} disabled={!!group.archivedAt}/></label><button className="button secondary" disabled={busy||!!group.archivedAt||name===group.name}>Bewaren</button></form>
 <label className="identity-select">Jij kijkt als<select aria-label="Jij kijkt als" value={group.selfMemberId} onChange={e=>identity(e.target.value)}>{group.members.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select><span className="field-note">Bepaalt jouw overzicht op dit apparaat. Er is nog geen account of verificatie.</span></label>
 <div className="section-heading space-above"><h2>Deelnemers</h2><span className="muted">{group.members.length}</span></div><div className="member-list">{group.members.map((m,i)=><MemberRow key={`${m.id}-${m.name}`} member={m} index={i} group={group} commit={commit}/>)}</div>
 {!group.archivedAt?<form className="inline-form member-add-form" onSubmit={add}><label className="visually-hidden" htmlFor="new-member">Nieuwe deelnemer</label><input id="new-member" value={member} onChange={e=>setMember(e.target.value)} required maxLength={60} placeholder="Naam van nieuwe deelnemer"/><button className="button secondary" disabled={busy} aria-label="Deelnemer toevoegen"><Plus size={18}/><span>Toevoegen</span></button></form>:null}
 <FormError message={error}/><div className="section-heading space-above"><h2>Overzicht bewaren</h2></div><div className="settings-actions"><button className="settings-action" onClick={()=>downloadFile('shared-money-uitgaven.csv',exportCsv(group),'text/csv;charset=utf-8')}><Download size={20}/><span><strong>Uitgaven exporteren</strong><small>CSV-bestand voor Excel of je eigen administratie</small></span><ChevronDown className="arrow-right" size={18}/></button><button className="settings-action" disabled={busy} onClick={archive}><Archive size={20}/><span><strong>{group.archivedAt?'Groep uit archief halen':'Groep archiveren'}</strong><small>Je uitgaven en betalingen blijven bewaard</small></span><ChevronDown className="arrow-right" size={18}/></button></div>
 <div className="section-heading space-above"><h2><History size={19}/> Wijzigingshistorie</h2></div>{group.activities.length?<ol className="activity-list">{group.activities.slice(0,100).map(a=><li key={a.id}><div className="activity-dot"/><div><strong>{a.title}</strong><p>{a.actor} · {a.action}</p><time dateTime={a.at}>{new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(a.at))}</time>{a.before||a.after?<details><summary>Details bekijken</summary>{a.before?<p><span>Voor:</span> {a.before}</p>:null}{a.after?<p><span>Na:</span> {a.after}</p>:null}</details>:null}</div></li>)}</ol>:<p className="section-description">Hier zie je straks wie een uitgave toevoegt, wijzigt of verwijdert.</p>}
 </div>;
}
function MemberRow({member,index,group,commit}:{member:Member;index:number;group:Group;commit:Commit}){
 const [name,setName]=useState(member.name),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await commit({type:'rename-member',groupId:group.id,memberId:member.id,name},'Naam gewijzigd');}catch(e){setError(errorMessage(e));setBusy(false);}}
 return <details className="member-item"><summary><span className="member-label"><Avatar name={member.name} index={index}/><strong>{member.name}</strong>{member.id===group.selfMemberId?<span className="inline-self">jij</span>:null}</span>{!group.archivedAt?<span className="muted">Bewerken</span>:null}</summary>{!group.archivedAt?<form className="inline-form" onSubmit={save}><label className="visually-hidden" htmlFor={`name-${member.id}`}>Naam van {member.name}</label><input id={`name-${member.id}`} required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/><button className="button secondary" disabled={busy||name===member.name}>Bewaren</button><FormError message={error}/></form>:null}</details>;
}
export function AppSettings({workspace,commit,onClose,onImported}:{workspace:Workspace;commit:Commit;onClose:()=>void;onImported:(id:string)=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 async function importFile(file?:File){if(!file)return;setError('');setBusy(true);try{if(file.size>MAX_BACKUP_BYTES)throw new Error('Dit bestand is te groot (maximaal 32 MB).');const backup=parseBackup(await file.text());if(!backup.groups.length)throw new Error('Deze reservekopie bevat geen groepen.');const groups=backup.groups.map(g=>independentCopy(g,g.selfMemberId));await commit({type:'import-groups',groups},`${groups.length} ${groups.length===1?'groep':'groepen'} geïmporteerd`);onImported(groups[0].id);onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);if(fileRef.current)fileRef.current.value='';}}
 return <Dialog title="Jouw gegevens" onClose={onClose}><div className="form"><div className="notice"><strong>Op dit apparaat bewaard</strong><p>Je gegevens blijven in deze browser. Er is nog geen login, cloudopslag of synchronisatie tussen apparaten. Maak regelmatig een reservekopie, ook voordat je browsergegevens wist.</p></div><button className="settings-action" onClick={()=>downloadFile(`shared-money-reservekopie-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(workspace))}><Download size={20}/><span><strong>Reservekopie downloaden</strong><small>Alle groepen, uitgaven, betalingen en bonfoto’s</small></span></button><button className="settings-action" disabled={busy} onClick={()=>fileRef.current?.click()}><Upload size={20}/><span><strong>{busy?'Reservekopie lezen…':'Reservekopie importeren'}</strong><small>Voegt onafhankelijke kopieën toe; bestaande groepen blijven staan</small></span></button><input type="file" ref={fileRef} accept=".json,application/json" className="visually-hidden" tabIndex={-1} onChange={e=>importFile(e.target.files?.[0])}/><FormError message={error}/><p className="fine-print">Reservekopieën bevatten persoonlijke groepsgegevens. Deel ze alleen met mensen die deze mogen lezen.</p><div className="about-app"><strong>Shared Money</strong><span>Versie 1.0 · Samen delen, zonder gedoe.</span></div></div></Dialog>;
}
