'use client';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {getDailyPrimaryAction} from '@/domain/today-actions';
import {getStatusMeta} from '@/lib/calendar-ui';
import {formatMoney} from '@/lib/format';
import type {DailyDetail} from './types';
const paymentLabels:Record<string,string>={unpaid:'Nog niet betaald',pending:'Betaling in verwerking',paid:'Betaald',partially_refunded:'Deels terugbetaald',refunded:'Terugbetaald',failed:'Betaling mislukt'};
export function AppointmentContext({detail,timezone,canManage,onChanged,onView,onRebook,onMove,setDirty}:{detail:DailyDetail;timezone:string;canManage:boolean;onChanged:()=>Promise<void>;onView:(view:'appointment'|'customer'|'intake',submissionId?:string)=>void;onRebook:()=>void;onMove:()=>void;setDirty:(dirty:boolean)=>void}){
 const a=detail.appointment;const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState('');const [note,setNote]=useState(a.note??'');const [noteConflict,setNoteConflict]=useState(false);
 const primary=getDailyPrimaryAction(a);const active=['pending','confirmed','checked_in'].includes(a.status);
 async function mutate(action:string){
  if(lock.current)return;lock.current=true;setBusy(true);setError(null);setNotice('');
  try{
   const response=await fetch('/api/internal/today',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appointmentId:a.id,action,expectedStatus:a.status,expectedStartedAt:a.treatment_started_at,note:action==='note'?note:undefined,expectedNote:action==='note'?a.note:undefined}),signal:AbortSignal.timeout(15000)});
   const body=await response.json();if(!response.ok)throw new Error(body.error);
   if(action==='note'){setDirty(false);setNoteConflict(false)}setNotice(action==='note'?'Notitie opgeslagen.':'Planning bijgewerkt.');await onChanged();
  }catch(e){setError(e instanceof Error?e.message:'Opslaan is niet gelukt. Probeer opnieuw.');if(action==='note')setNoteConflict(true);try{await onChanged()}catch{setError('De actuele gegevens konden niet worden geladen. Probeer opnieuw zodra de verbinding hersteld is.')}}
  finally{lock.current=false;setBusy(false)}
 }
 const time=(value:string)=>new Intl.DateTimeFormat('nl-NL',{timeZone:timezone,hour:'2-digit',minute:'2-digit'}).format(new Date(value));
 return <div className="grid min-w-0 gap-5" data-daily-appointment>
  <div><p className="text-sm text-[var(--muted)] tabular-nums">{time(a.starts_at)}–{time(a.service_ends_at)}</p><button type="button" onClick={()=>onView('customer')} className="mt-2 block max-w-full break-words text-left text-2xl font-semibold tracking-[-.04em] hover:text-[var(--primary)]">{detail.customer?.name??a.customer_name_snapshot??'Klant'}</button><p className="mt-1 break-words text-sm text-[var(--muted)]">{a.service_name_snapshot}</p><p className="mt-3 text-xs font-medium" data-daily-status>{a.status==='checked_in'&&a.treatment_started_at?'Behandeling bezig':getStatusMeta(a.status).label}</p></div>
  {canManage?<>
   {primary?<Button size="lg" disabled={busy} onClick={()=>mutate(primary.action)}>{busy?'Opslaan…':primary.label}</Button>:a.status==='completed'?<Button size="lg" onClick={onRebook}>Opnieuw boeken</Button>:null}
   <div className="flex flex-wrap gap-x-4 gap-y-1 text-sm">
    {a.status!=='completed'?<button className="min-h-11 font-medium text-[var(--primary)]" type="button" onClick={onRebook} disabled={busy}>Opnieuw boeken</button>:null}
    {active?<button className="min-h-11 font-medium text-[var(--primary)]" type="button" onClick={onMove} disabled={busy}>Verplaatsen</button>:null}
    <button className="min-h-11 font-medium text-[var(--primary)]" type="button" onClick={()=>onView('customer')}>Klant bekijken</button>
   </div>
  </>:null}
  {error?<p role="alert" className="break-words text-sm text-[var(--danger)]">{error}</p>:null}<p role="status" className="text-sm text-[var(--muted)]">{notice}</p>
  {canManage?<details className="border-t border-[var(--border)]"><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">Notities{a.note?' · aanwezig':''}</summary><form onSubmit={e=>{e.preventDefault();void mutate('note')}} className="grid gap-2"><label className="grid gap-2 text-sm"><span>Afspraaknotitie</span><textarea name="note" value={note} maxLength={1000} rows={4} onChange={e=>{setNote(e.target.value);setDirty(e.target.value!==(a.note??''))}} className="w-full rounded-[8px] border border-[var(--border)] p-3"/></label>{noteConflict?<div className="grid gap-2 border-l-2 border-[var(--border)] pl-3"><p className="text-sm">Controleer de actuele notitie voordat je jouw concept opslaat:</p><p className="whitespace-pre-wrap break-words text-sm">{a.note||'Geen notitie'}</p><Button type="button" variant="secondary" onClick={()=>{setNoteConflict(false);setError(null)}}>Mijn concept behouden</Button><button type="button" className="min-h-11 text-left text-sm text-[var(--muted)]" onClick={()=>{setNote(a.note??'');setDirty(false);setNoteConflict(false);setError(null)}}>Actuele notitie gebruiken</button></div>:null}<Button variant="secondary" disabled={busy||noteConflict||note===(a.note??'')}>Notitie opslaan</Button></form></details>:null}
  {canManage&&(detail.intake.forms.length||detail.intake.submissions.length)?<details className="border-t border-[var(--border)]"><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">Intake & toestemming · {detail.intake.submissions.length?'ontvangen':'nog niet ontvangen'}</summary><div className="grid gap-2">{detail.intake.forms.map(f=><p key={f.id} className="text-sm">{f.title}: {detail.intake.submissions.some(s=>s.form_id===f.id)?'Ontvangen':'Ontbreekt'}</p>)}{detail.intake.submissions.map(s=><button type="button" key={s.id} onClick={()=>onView('intake',s.id)} className="min-h-11 text-left text-sm font-medium text-[var(--primary)]">Formulier bekijken · versie {s.form_version}</button>)}</div></details>:null}
  {canManage?<details className="border-t border-[var(--border)]"><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">Betaling</summary><p className="text-sm">{formatMoney(a.price_cents_snapshot,a.currency_snapshot)} · {paymentLabels[a.payment_status]??a.payment_status}</p></details>:null}
  {canManage&&active?<details className="border-t border-[var(--border)]"><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">Meer</summary><div className="grid gap-1"><button type="button" disabled={busy} onClick={()=>{if(window.confirm('Deze afspraak annuleren?'))void mutate('cancel')}} className="min-h-11 text-left text-sm text-[var(--danger)]">Annuleren</button>{a.status==='confirmed'?<button type="button" disabled={busy} onClick={()=>{if(window.confirm('Klant als niet verschenen markeren?'))void mutate('no_show')}} className="min-h-11 text-left text-sm text-[var(--danger)]">Niet verschenen</button>:null}</div></details>:null}
 </div>;
}
export function CustomerContext({detail,timezone,canManage,onBack,onRebook}:{detail:DailyDetail;timezone:string;canManage:boolean;onBack:()=>void;onRebook:()=>void}){
 const customer=detail.customer;const date=(v:string)=>new Intl.DateTimeFormat('nl-NL',{timeZone:timezone,dateStyle:'medium',timeStyle:'short'}).format(new Date(v));
 return <div className="grid min-w-0 gap-5"><button type="button" onClick={onBack} className="min-h-11 text-left text-sm text-[var(--muted)]">← Afspraak</button><div><h3 className="break-words text-2xl font-semibold">{customer?.name??'Klant'}</h3><p className="mt-2 break-words text-sm text-[var(--muted)]">{customer?.email??'Geen e-mail'}</p>{customer?.phone?<a href={`tel:${customer.phone}`} className="mt-2 inline-flex min-h-11 items-center text-sm text-[var(--primary)]">{customer.phone} · Bellen</a>:null}</div><dl className="grid gap-3 text-sm"><div><dt className="text-[var(--muted)]">Laatste bezoek</dt><dd className="mt-1">{detail.previous?date(detail.previous.starts_at):'Nog geen eerder bezoek'}</dd></div><div><dt className="text-[var(--muted)]">Volgende afspraak</dt><dd className="mt-1">{detail.next?date(detail.next.starts_at):'Nog niet gepland'}</dd></div></dl>{customer?.internal_notes?<p className="whitespace-pre-wrap break-words text-sm">{customer.internal_notes}</p>:null}{detail.consents.length?<details><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">Toestemming</summary>{detail.consents.map(c=><div className="mb-3 text-sm" key={c.id}><p className="whitespace-pre-wrap break-words">{c.statement}</p><p className="mt-1 text-xs text-[var(--muted)]">Gegeven op {date(c.consented_at)}</p></div>)}</details>:null}<>{canManage?<Button onClick={onRebook}>Opnieuw boeken</Button>:null}</>{customer&&canManage?<a href={`/app/customers/${customer.id}`} className="min-h-11 py-3 text-sm text-[var(--muted)]">Volledig profiel →</a>:null}</div>;
}
