'use client';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Field} from '@/components/ui/field';
import type {BookingSeed,DailyCatalog} from './types';
function local(iso:string,timezone:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso));const part=(name:string)=>parts.find(p=>p.type===name)?.value;return `${part('year')}-${part('month')}-${part('day')}T${part('hour')}:${part('minute')}`}
export function BlockContext({seed,mode,catalog,timezone,onSaved,setDirty}:{seed:BookingSeed;mode:'pause'|'block';catalog:DailyCatalog;timezone:string;onSaved:()=>void;setDirty:(dirty:boolean)=>void}){
 const [start,setStart]=useState(seed.startsAt?local(seed.startsAt,timezone):`${seed.date}T12:00`);const [end,setEnd]=useState(seed.startsAt?local(new Date(Date.parse(seed.startsAt)+30*60000).toISOString(),timezone):`${seed.date}T12:30`);const [staff,setStaff]=useState(seed.staffId??catalog.staff[0]?.id??'');const [reason,setReason]=useState(mode==='pause'?'Pauze':'');const [saving,setSaving]=useState(false);const [error,setError]=useState('');const lock=useRef(false);const requestId=useRef(crypto.randomUUID());
 async function submit(event:React.FormEvent){event.preventDefault();if(lock.current)return;lock.current=true;setSaving(true);setError('');try{const response=await fetch('/api/internal/today',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'block',staffId:staff||null,startsAt:start,endsAt:end,reason,requestId:requestId.current}),signal:AbortSignal.timeout(15000)});const body=await response.json();if(!response.ok)throw new Error(body.error);setDirty(false);onSaved()}catch(e){setError(e instanceof Error?e.message:'Opslaan is niet gelukt. Probeer opnieuw.')}finally{lock.current=false;setSaving(false)}}
 return <form className="grid gap-4" onSubmit={submit} onChange={()=>setDirty(true)}><label className="grid gap-2 text-sm font-medium"><span>Medewerker</span><select name="staffId" className="h-11 min-w-0 rounded-[8px] border border-[var(--border)] bg-white px-3" value={staff} onChange={e=>setStaff(e.target.value)}><option value="">Hele salon</option>{catalog.staff.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><Field name="startsAt" label="Start" type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/><Field name="endsAt" label="Einde" type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/>{mode==='pause'?<div className="flex gap-2">{[15,30,60].map(minutes=><button key={minutes} type="button" className="min-h-11 flex-1 rounded-[8px] border border-[var(--border)] text-sm" onClick={()=>{const value=new Date(start);value.setMinutes(value.getMinutes()+minutes);const pad=(v:number)=>String(v).padStart(2,'0');setEnd(`${value.getFullYear()}-${pad(value.getMonth()+1)}-${pad(value.getDate())}T${pad(value.getHours())}:${pad(value.getMinutes())}`);setDirty(true)}}>{minutes} min</button>)}</div>:<Field label="Reden (optioneel)" name="reason" maxLength={160} value={reason} onChange={e=>setReason(e.target.value)}/>} {error?<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>:null}<Button disabled={saving}>{saving?'Opslaan…':mode==='pause'?'Pauze toevoegen':'Tijd blokkeren'}</Button></form>;
}
