'use client';
import {useCallback,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {TodaySummary} from '@/components/workspace/today-summary';
import {getStatusMeta} from '@/lib/calendar-ui';
import {ContextSurface} from './context-surface';
import type {DailyContext,DailyData,BookingSeed} from './types';
const ContextLoader=dynamic(()=>import('./context-loader').then(m=>m.ContextLoader),{loading:()=> <p role="status" className="py-5 text-sm text-[var(--muted)]">Gegevens laden…</p>});
export function DailyWorkspace({data,timezone,currency,role,dateLabel,initialAppointmentId}:{data:DailyData;timezone:string;currency:string;role:'owner'|'manager'|'staff';dateLabel:string;initialAppointmentId?:string}){
 const router=useRouter();const canManage=role!=='staff';const [context,setContext]=useState<DailyContext|null>(initialAppointmentId?{kind:'appointment',id:initialAppointmentId,view:'appointment'}:null);const dirty=useRef(false);const [notice,setNotice]=useState('');
 const setDirty=useCallback((value:boolean)=>{dirty.current=value},[]);
 function select(next:DailyContext|null){if(dirty.current&&!window.confirm('Niet-opgeslagen wijzigingen verlaten?'))return;dirty.current=false;setContext(next);const url=new URL(window.location.href);if(next?.kind==='appointment')url.searchParams.set('appointment',next.id);else url.searchParams.delete('appointment');window.history.replaceState(null,'',url)}
 function appointment(id:string){select({kind:'appointment',id,view:'appointment'})}
 function booking(seed:BookingSeed={}){select({kind:'booking',seed:{date:data.date,...seed},title:'Nieuwe afspraak'})}
 function saved(){dirty.current=false;select(null);setNotice('Planning bijgewerkt.');router.refresh()}
 const time=(value:string|Date)=>new Intl.DateTimeFormat('nl-NL',{timeZone:timezone,hour:'2-digit',minute:'2-digit'}).format(new Date(value));
 const hero=data.currentAppointment??data.nextAppointment;
 const selectedId=context?.kind==='appointment'?context.id:null;
 const rows=[...data.appointments.map(a=>({kind:'appointment' as const,start:a.starts_at,id:a.id,appointment:a})),...data.blocks.map(b=>({kind:'block' as const,start:b.starts_at,id:b.id,block:b})),...data.breaks.map((b,index)=>({kind:'break' as const,start:b.start.toISOString(),id:`break-${b.staffId}-${index}`,break:b}))].toSorted((a,b)=>Date.parse(a.start)-Date.parse(b.start));
 const attention=data.appointments.filter(a=>a.status==='pending');
 const title=context?.kind==='appointment'?(context.view==='customer'?'Klant':context.view==='intake'?'Intake & toestemming':'Afspraak'):context?.kind==='booking'?context.title:context?.kind==='reschedule'?'Afspraak verplaatsen':context?.kind==='block'?(context.mode==='pause'?'Pauze toevoegen':'Tijd blokkeren'):'';
 return <div data-testid="today-command-centre" data-one-screen-day>
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold tracking-[-.045em] sm:text-[36px]">Vandaag</h1><p className="mt-1 text-sm capitalize text-[var(--muted)]">{dateLabel}</p></div>{canManage?<Button onClick={()=>booking()}>Nieuwe afspraak</Button>:null}</header>
  <section data-orsira-next-appointment className="mt-6 border-y border-[var(--border)] py-5">
   {hero?<div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><div><p className="text-xs font-semibold text-[var(--muted)]">{data.currentAppointment?'Huidige afspraak':'Volgende afspraak'}</p><button type="button" onClick={()=>appointment(hero.id)} className="mt-2 flex min-h-11 max-w-full items-baseline gap-4 text-left hover:text-[var(--primary)]"><time className="shrink-0 text-3xl font-semibold tracking-[-.04em] tabular-nums">{time(hero.starts_at)}</time><span className="min-w-0"><span className="block truncate text-base font-semibold">{hero.customer?.name??hero.customer_name_snapshot??'Klant'}</span><span className="mt-1 block truncate text-sm text-[var(--muted)]">{hero.service_name_snapshot}</span></span></button></div>{data.currentAppointment&&data.nextAppointment?<div className="sm:border-l sm:border-[var(--border)] sm:pl-5"><p className="text-xs text-[var(--muted)]">Daarna</p><button type="button" onClick={()=>appointment(data.nextAppointment!.id)} className="mt-1 min-h-11 max-w-full truncate text-left text-sm"><strong className="mr-3 tabular-nums">{time(data.nextAppointment.starts_at)}</strong>{data.nextAppointment.customer?.name??data.nextAppointment.customer_name_snapshot}</button></div>:null}</div>:<div><p className="font-semibold">Geen afspraken meer gepland.</p><p className="mt-1 text-sm text-[var(--muted)]">Je volledige dagplanning staat hieronder.</p></div>}
  </section>
  <TodaySummary appointmentCount={data.appointmentCount} plannedValueCents={data.plannedValueCents} occupancyPercent={data.occupancyPercent} bookableMinutes={data.bookableMinutes} freeCapacityMinutes={data.freeCapacityMinutes} attentionCount={attention.length} currency={currency} staffRole={!canManage}/>
  {canManage&&attention.length?<details className="mb-4 border-b border-[var(--border)]"><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">Aandacht nodig · {attention.length} nog niet bevestigd</summary><div className="mb-3 grid gap-1">{attention.map(a=><button type="button" key={a.id} onClick={()=>appointment(a.id)} className="min-h-11 text-left text-sm text-[var(--primary)]">{time(a.starts_at)} · {a.customer_name_snapshot??'Klant'} bekijken</button>)}</div></details>:null}
  <p role="status" className="text-sm text-[var(--muted)]">{notice}</p>
  <div className="mt-5 grid min-w-0 items-start gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(320px,.7fr)]">
   <section className="min-w-0"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">Je dag</h2><Link href="/app/calendar" className="inline-flex min-h-11 items-center text-xs text-[var(--muted)]">Agenda →</Link></div>
    {rows.length?<div className="overflow-hidden rounded-[10px] border border-[var(--border)] bg-white" data-daily-timeline>{rows.map(row=>row.kind==='appointment'?<button type="button" data-appointment-id={row.id} aria-pressed={selectedId===row.id} key={row.id} onClick={()=>appointment(row.id)} className={`grid min-h-[76px] w-full grid-cols-[50px_minmax(0,1fr)] items-center gap-x-3 border-b border-[var(--border)] px-4 py-3 text-left last:border-0 sm:grid-cols-[60px_minmax(0,1fr)_auto] ${selectedId===row.id?'bg-[var(--primary-soft)]':'hover:bg-[var(--surface-soft)]'}`}><time className="text-sm font-semibold tabular-nums">{time(row.start)}</time><span className="min-w-0"><span className="block truncate text-[15px] font-semibold">{row.appointment.customer?.name??row.appointment.customer_name_snapshot??'Klant'}</span><span className="mt-1 block truncate text-sm text-[var(--muted)]">{row.appointment.service_name_snapshot}{row.appointment.staff?.name?` · ${row.appointment.staff.name}`:''}</span></span>{row.appointment.status!=='confirmed'?<span className="col-start-2 mt-1 text-xs text-[var(--muted)] sm:col-start-auto">{row.appointment.status==='checked_in'&&row.appointment.treatment_started_at?'Bezig':getStatusMeta(row.appointment.status).label}</span>:null}</button>:<div key={row.id} className="grid min-h-16 grid-cols-[50px_minmax(0,1fr)] gap-3 border-b border-[var(--border)] bg-[var(--surface-soft)] px-4 py-3 text-sm last:border-0 sm:grid-cols-[60px_minmax(0,1fr)]"><time className="tabular-nums">{time(row.start)}</time><div><p className="font-medium">{row.kind==='break'?'Pauze':row.block.reason||'Geblokkeerd'}</p><p className="mt-1 text-xs text-[var(--muted)]">tot {time(row.kind==='break'?row.break.end:row.block.ends_at)}{row.kind==='break'?` · ${row.break.staffName}`:row.block.staff_id?' · Medewerker':' · Hele salon'}</p></div></div>)}</div>:<div className="border-y border-[var(--border)] py-8"><p className="font-semibold">Nog geen afspraken vandaag</p><p className="mt-1 text-sm text-[var(--muted)]">Voeg een afspraak toe of gebruik de vrije ruimte.</p></div>}
    {canManage?<div className="mt-7"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Vrije ruimte</h2><details className="relative"><summary className="min-h-11 cursor-pointer py-3 text-sm text-[var(--muted)]">Meer</summary><div className="absolute right-0 z-10 grid w-44 rounded-[10px] border border-[var(--border)] bg-white p-2">{(['pause','block'] as const).map(mode=><button type="button" key={mode} onClick={()=>select({kind:'block',mode,seed:{date:data.date}})} className="min-h-11 px-2 text-left text-sm hover:bg-[var(--surface-soft)]">{mode==='pause'?'Pauze toevoegen':'Tijd blokkeren'}</button>)}</div></details></div>{data.gaps.length?<div className="divide-y divide-[var(--border)] border-y border-[var(--border)]">{data.gaps.map(gap=>{const seed={date:data.date,staffId:gap.staffId,startsAt:gap.start.toISOString(),endsAt:gap.end.toISOString()};const matches=data.waitlistMatches.filter(m=>m.gap.staffId===gap.staffId&&m.gap.start.getTime()===gap.start.getTime());return <div key={`${gap.staffId}-${gap.start.toISOString()}`} className="py-4"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="text-sm font-medium tabular-nums">{time(gap.start)}–{time(gap.end)} <span className="font-normal text-[var(--muted)]">Vrij</span></p><p className="mt-1 truncate text-xs text-[var(--muted)]">{gap.staffName}</p></div><button type="button" className="min-h-11 shrink-0 text-sm font-medium text-[var(--primary)]" onClick={()=>booking(seed)}>+ Afspraak</button></div><details><summary className="min-h-11 cursor-pointer py-3 text-xs text-[var(--muted)]">{matches.length?`${matches.length} wachtlijstmatch${matches.length===1?'':'es'} · Meer`:'Meer opties'}</summary><div className="grid gap-1">{matches.map(match=><button type="button" className="min-h-11 text-left text-sm text-[var(--primary)]" key={match.entryId} onClick={()=>booking({...seed,serviceId:match.serviceId,newCustomer:{name:match.customerName,phone:match.phone,email:match.email}})}>{match.customerName} · {match.serviceName}</button>)}<button type="button" className="min-h-11 text-left text-sm" onClick={()=>select({kind:'block',mode:'pause',seed})}>Pauze toevoegen</button><button type="button" className="min-h-11 text-left text-sm" onClick={()=>select({kind:'block',mode:'block',seed})}>Tijd blokkeren</button></div></details></div>})}</div>:<p className="py-4 text-sm text-[var(--muted)]">Geen vrije blokken van 30 minuten of langer meer vandaag.</p>}</div>:null}
   </section>
   {context?<ContextSurface title={title} onClose={()=>select(null)}><ContextLoader key={context.kind==='appointment'?`${context.kind}-${context.id}-${context.view}`:context.kind} context={context} timezone={timezone} canManage={canManage} onSelect={select} onSaved={saved} onRefresh={()=>router.refresh()} setDirty={setDirty}/></ContextSurface>:<aside className="hidden border-l border-[var(--border)] py-5 pl-6 lg:block"><p className="text-sm font-medium">Alles bij de hand</p><p className="mt-2 max-w-xs text-sm leading-6 text-[var(--muted)]">Kies een afspraak om je klant te bekijken en de volgende stap uit te voeren.</p></aside>}
  </div>
 </div>;
}
