"use client";

import { useEffect, useMemo, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Field, TextAreaField } from "@/components/ui/field";

type Service={id:string;name:string;duration_minutes:number};
type Staff={id:string;name:string};
type Slot={start:string};
type Customer={id:string;name:string;phone:string|null;email:string|null};

export function NewAppointmentForm({services,staffByService,timezone,initialCustomer=null,initialServiceId,initialStaffId,initialDate,initialStartsAt,initialEndsAt,initialNewCustomer,onSaved,onDirty,onRefresh}:{services:Service[];staffByService:Record<string,Staff[]>;timezone:string;initialCustomer?:Customer|null;initialServiceId?:string;initialStaffId?:string;initialDate?:string;initialStartsAt?:string;initialEndsAt?:string;initialNewCustomer?:Omit<Customer,"id">;onSaved?:(appointmentId:string)=>void;onDirty?:(dirty:boolean)=>void;onRefresh?:()=>void}) {
  const router=useRouter();
  const [serviceId,setServiceId]=useState(initialServiceId??services[0]?.id??"");
  const staff=staffByService[serviceId]??[];
  const [staffId,setStaffId]=useState(initialStaffId??staff[0]?.id??"");
  const today=useMemo(()=>new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),[timezone]);
  const [date,setDate]=useState(initialDate??today);const [slots,setSlots]=useState<Slot[]>([]);const [startsAt,setStartsAt]=useState("");const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);
  const [query,setQuery]=useState(initialCustomer?.name??initialNewCustomer?.name??"");const [results,setResults]=useState<Customer[]>([]);const [searching,setSearching]=useState(false);
  const [customerId,setCustomerId]=useState(initialCustomer?.id??"");const [customerName,setCustomerName]=useState(initialCustomer?.name??initialNewCustomer?.name??"");const [customerPhone,setCustomerPhone]=useState(initialCustomer?.phone??initialNewCustomer?.phone??"");const [customerEmail,setCustomerEmail]=useState(initialCustomer?.email??initialNewCustomer?.email??"");
  const submitLock=useRef(false);const [availabilityVersion,setAvailabilityVersion]=useState(0);const [mutationError,setMutationError]=useState<string|null>(null);
  const staffDefault=useRef(initialStaffId);
  const dirty=Boolean(startsAt||customerName||customerPhone||customerEmail);

  useEffect(()=>{const next=(staffByService[serviceId]??[])[0]?.id??"";setStaffId(staffDefault.current&&staffByService[serviceId]?.some(s=>s.id===staffDefault.current)?staffDefault.current:next);staffDefault.current=undefined;setStartsAt("")},[serviceId,staffByService]);
  useEffect(()=>{onDirty?.(dirty)},[dirty,onDirty]);
  useEffect(()=>{if(!dirty)return;const handler=(event:BeforeUnloadEvent)=>{event.preventDefault()};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler)},[dirty]);
  useEffect(()=>{if(query.trim().length<2||customerId){setResults([]);return}const controller=new AbortController();const timer=window.setTimeout(()=>{setSearching(true);fetch(`/api/internal/customers?q=${encodeURIComponent(query.trim())}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(12000)])}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);if(!controller.signal.aborted)setResults(body.customers??[])}).catch(error=>{if(!(error instanceof DOMException&&error.name==="AbortError"))setResults([])}).finally(()=>{if(!controller.signal.aborted)setSearching(false)})},220);return()=>{window.clearTimeout(timer);controller.abort()}},[query,customerId]);

  function chooseCustomer(customer:Customer){setCustomerId(customer.id);setQuery(customer.name);setCustomerName(customer.name);setCustomerPhone(customer.phone??"");setCustomerEmail(customer.email??"");setResults([])}
  function newCustomer(){setCustomerId("");setQuery("");setCustomerName("");setCustomerPhone("");setCustomerEmail("");setResults([])}

  useEffect(()=>{if(!serviceId||!staffId||!date){setSlots([]);return}const controller=new AbortController();setLoading(true);setSlots([]);setError(null);setStartsAt("");fetch(`/api/internal/availability?serviceId=${serviceId}&staffId=${staffId}&date=${date}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(12000)])}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);if(!controller.signal.aborted){const available=(body.slots??[]) as Slot[];setSlots(initialStartsAt&&date===initialDate?available.filter(slot=>Date.parse(slot.start)>=Date.parse(initialStartsAt)&&(!initialEndsAt||Date.parse(slot.start)+((services.find(s=>s.id===serviceId)?.duration_minutes??0)*60000)<=Date.parse(initialEndsAt))):available)}}).catch(error=>{if(controller.signal.aborted)return;setError(error instanceof Error?error.message:"Beschikbaarheid kon niet worden geladen.");setSlots([])}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[date,serviceId,staffId,initialStartsAt,initialEndsAt,initialDate,services,availabilityVersion]);

  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!startsAt||submitLock.current)return;submitLock.current=true;const data=new FormData(event.currentTarget);setSaving(true);setMutationError(null);try{const response=await fetch("/api/internal/book",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceId,staffId,startsAt,customerId:customerId||null,customer:{name:data.get("name"),phone:data.get("phone"),email:data.get("email"),note:data.get("note")}}),signal:AbortSignal.timeout(15000)});const body=await response.json();if(!response.ok)throw new Error(body.error);onDirty?.(false);if(onSaved)onSaved(body.appointmentId);else{router.push(`/app/appointments/${body.appointmentId}`);router.refresh()}}catch(error){setMutationError(error instanceof Error?error.message:"Opslaan is niet gelukt. Controleer de planning voor je opnieuw probeert.");setStartsAt("");setSlots([]);setAvailabilityVersion(v=>v+1);onRefresh?.();router.refresh()}finally{submitLock.current=false;setSaving(false)}}

  return <form onSubmit={submit} className="mt-7 grid min-w-0 max-w-xl gap-5">
    <div className="pb-4 border-b border-[var(--border)]"><label className="grid gap-1.5 text-sm font-medium"><span>Zoek bestaande klant</span><input value={query} onChange={event=>{setQuery(event.target.value);if(customerId&&event.target.value!==customerName){setCustomerId("");setCustomerName("");setCustomerPhone("");setCustomerEmail("")}}} autoComplete="off" placeholder="Naam, telefoon of e-mail…" className="h-11 rounded-[11px] border border-[var(--border)] bg-white px-3.5"/><span className="text-xs font-normal text-[var(--muted)]">{searching?"Zoeken…":customerId?"Klant geselecteerd.":"Typ minimaal 2 tekens of vul hieronder een nieuwe klant in."}</span></label>
      {results.length?<div className="mt-2 overflow-hidden rounded-[11px] border border-[var(--border)] bg-white">{results.map(customer=><button key={customer.id} type="button" onClick={()=>chooseCustomer(customer)} className="block w-full border-b border-[var(--border)] px-3.5 py-3 text-left last:border-0"><span className="block text-sm font-semibold">{customer.name}</span><span className="mt-0.5 block text-xs text-[var(--muted)]">{[customer.phone,customer.email].filter(Boolean).join(" · ")}</span></button>)}</div>:null}
      {customerId?<button type="button" onClick={newCustomer} className="mt-2 text-xs font-medium text-[var(--primary)]">Andere / nieuwe klant</button>:null}
      {customerId ? <div className="mt-3"><p className="font-semibold">{customerName}</p><p className="mt-1 break-words text-sm text-[var(--muted)]">{[customerPhone,customerEmail].filter(Boolean).join(" · ")}</p><input type="hidden" name="name" value={customerName}/><input type="hidden" name="phone" value={customerPhone}/><input type="hidden" name="email" value={customerEmail}/></div> : <div className="mt-4 grid gap-4"><Field label="Klantnaam" name="name" value={customerName} readOnly={Boolean(customerId)} onChange={event=>setCustomerName(event.target.value)} required/><Field label="Telefoon (optioneel)" name="phone" type="tel" value={customerPhone} readOnly={Boolean(customerId)} onChange={event=>setCustomerPhone(event.target.value)}/><Field label="E-mail (optioneel)" name="email" type="email" value={customerEmail} readOnly={Boolean(customerId)} onChange={event=>setCustomerEmail(event.target.value)}/></div>}
    </div>

    <label className="grid min-w-0 gap-1.5 text-sm font-medium"><span>Behandeling</span><select value={serviceId} onChange={event=>setServiceId(event.target.value)} className="h-11 min-w-0 w-full max-w-full rounded-[11px] border border-[var(--border)] bg-white px-3.5">{services.map(item=><option key={item.id} value={item.id}>{item.name} · {item.duration_minutes} min</option>)}</select></label>
    {staff.length > 1 ? <label className="grid min-w-0 gap-1.5 text-sm font-medium"><span>Medewerker</span><select value={staffId} onChange={event=>setStaffId(event.target.value)} className="h-11 min-w-0 w-full max-w-full rounded-[11px] border border-[var(--border)] bg-white px-3.5">{staff.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : staff.length === 1 ? <p className="text-sm text-[var(--muted)]">Medewerker: {staff[0].name}</p> : null}
    <Field label="Datum" type="date" value={date} min={today} onChange={event=>setDate(event.target.value)} required/>
    <div><p className="mb-2 text-sm font-medium">Tijd</p>{loading?<div className="h-11 animate-pulse rounded-[10px] bg-[#e9e9e5]"/>:<div className="grid grid-cols-4 gap-2">{slots.map(item=><button key={item.start} type="button" onClick={()=>setStartsAt(item.start)} aria-pressed={startsAt===item.start} className={`min-h-11 rounded-[9px] border text-sm ${startsAt===item.start?"border-[var(--primary)] bg-[var(--primary)] text-white":"border-[var(--border)] bg-white"}`}>{new Intl.DateTimeFormat("nl-NL",{hour:"2-digit",minute:"2-digit",timeZone:timezone}).format(new Date(item.start))}</button>)}</div>}{!loading&&!slots.length?<p className="text-sm text-[var(--muted)]">Geen beschikbare tijden voor deze combinatie.</p>:null}</div>
    <details className="border-t border-[var(--border)] pt-2"><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">Meer opties</summary><TextAreaField label="Notitie (optioneel)" name="note"/></details>
    {mutationError?<p role="alert" className="text-sm text-[var(--danger)]">{mutationError}</p>:null}{error?<div><p role="alert" className="text-sm text-[var(--danger)]">{error}</p><Button type="button" variant="secondary" onClick={()=>setAvailabilityVersion(v=>v+1)}>Beschikbaarheid opnieuw laden</Button></div>:null}<Button size="lg" disabled={!startsAt||saving}>{saving?"Opslaan…":"Afspraak opslaan"}</Button>
  </form>
}
