"use client";

import { useEffect, useMemo, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { Field } from "@/components/ui/field";
import { Button } from "@/components/ui/button";

type Staff={id:string;name:string};type Slot={start:string};
function localValue(iso:string,timezone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(iso));const get=(type:Intl.DateTimeFormatPartTypes)=>parts.find(part=>part.type===type)?.value??"";return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`}

export function RescheduleForm({appointmentId,serviceId,staff,initialStaffId,initialStartsAt,timezone,onSaved,onDirty}:{appointmentId:string;serviceId:string;staff:Staff[];initialStaffId:string;initialStartsAt:string;timezone:string;onSaved?:()=>void;onDirty?:(dirty:boolean)=>void}){
  const router=useRouter();const today=useMemo(()=>new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),[timezone]);
  const [date,setDate]=useState(localValue(initialStartsAt,timezone).slice(0,10));const [staffId,setStaffId]=useState(initialStaffId);const [slots,setSlots]=useState<Slot[]>([]);const [startsAt,setStartsAt]=useState("");const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);
  const submitLock=useRef(false);
  useEffect(()=>{onDirty?.(Boolean(startsAt))},[startsAt,onDirty]);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setSlots([]);setError(null);setStartsAt("");fetch(`/api/internal/availability?serviceId=${serviceId}&staffId=${staffId}&date=${date}`,{signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);if(!controller.signal.aborted)setSlots(body.slots??[])}).catch(error=>{if(error instanceof DOMException&&error.name==="AbortError")return;setError(error instanceof Error?error.message:"Beschikbaarheid kon niet worden geladen.")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[date,serviceId,staffId]);
  async function save(){if(!startsAt||submitLock.current)return;submitLock.current=true;setSaving(true);setError(null);try{const response=await fetch("/api/internal/move",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({appointmentId,staffId,localStart:localValue(startsAt,timezone),expectedStartsAt:initialStartsAt,expectedStaffId:initialStaffId})});const body=await response.json();if(!response.ok)throw new Error(body.error);onDirty?.(false);if(onSaved)onSaved();else router.push(`/app/appointments/${appointmentId}`);router.refresh()}catch(error){setError(error instanceof Error?error.message:"Verplaatsen is niet gelukt.")}finally{submitLock.current=false;setSaving(false)}}
  return <div className="mt-7 grid max-w-xl gap-5"><label className="grid gap-1.5 text-sm font-medium"><span>Medewerker</span><select className="h-11 rounded-[11px] border border-[var(--border)] bg-white px-3.5" value={staffId} onChange={event=>setStaffId(event.target.value)}>{staff.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field label="Datum" type="date" min={today} value={date} onChange={event=>setDate(event.target.value)}/><div><p className="mb-2 text-sm font-medium">Tijd</p>{loading?<div className="h-11 animate-pulse rounded-[10px] bg-[#e9e9e5]"/>:<div className="grid grid-cols-4 gap-2">{slots.map(item=><button type="button" key={item.start} onClick={()=>setStartsAt(item.start)} aria-pressed={startsAt===item.start} className={`h-11 rounded-[9px] border text-sm ${startsAt===item.start?"border-[var(--primary)] bg-[var(--primary)] text-white":"border-[var(--border)] bg-white"}`}>{new Intl.DateTimeFormat("nl-NL",{hour:"2-digit",minute:"2-digit",timeZone:timezone}).format(new Date(item.start))}</button>)}</div>}</div>{error?<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>:null}<Button size="lg" disabled={!startsAt||saving} onClick={save}>{saving?"Verplaatsen…":"Afspraak verplaatsen"}</Button></div>
}
